export  const ADDADDRESSINCACHE = 'ADDADDRESSINCACHE' ; //增加地址到缓存

export  const DELETEADDRESSINCACHE = 'DELETEADDRESSINCACHE' ; //删除缓存

export  const ALTERADDRESSINCACHE = 'ALTERADDRESSINCACHE' ; //修改缓存